### PR TITLE
Add render function

### PR DESCRIPTION
**Pull request by owickstrom**
Corresponding to the `res.render('view', {...})` of express.

### CODE REVIEW

**Comment by dancingrobot84** [comment]
Hi! Thanks for taking the time to make a change. Could you please rebase your changes so that they could be merged? If you could add some tests for this functionality as well, that woud be great.

**Comment by alexbiehl** [comment]
@owickstrom ping

**Comment by owickstrom** [comment]
Oh, sorry. Totally lost this one! :)

Gonna take a look at it ASAP.

**Comment by owickstrom** [comment]
Now rebased and with tests added.

**Comment by dancingrobot84** [comment]
Cool, thanks! :+1:

**Pull request merged**
