### PR TITLE
Aff refactor among other changes

### LINKED ISSUE #15: Offer HandlerM built on Aff (Asynchronous Eff)
It would be really cool if HandlerM were a transformer on Aff (https://github.com/slamdata/purescript-aff), or to offer AsyncHandlerM so we could more easily write Handlers with lots of callbacks:

```purescript
asyncHandler :: AsyncHandler
asyncHandler = do
  info <- liftAff $ JQuery.get "/info.json"
  users <- liftAff $ Database.query "SELECT * FROM USERS"
  sendJson { info: info, users: users }

app = do
  get "/foo" asyncHandler
```

Doing something like this with `capture` can get ugly.

### PR DESCRIPTION
**Pull request by anttih**
I'm working on a big refactor which will change to using purescript-aff and get rid of the easy-ffi, among other things. Still a work in progress but I'd like to hear comments on this. This will fix #15 and #22.

Progress so far:

- [x] Use Aff in HandlerM
- [x] Parameterize HandlerM with effect rows in order to get rid of `unsafeInterleaveEff`
- [x] Split Node.Express.Handler to Request and Response modules and move internal modules into those
- [ ] Get rid of easy-ffi (a few functions already moved over)
- [ ] Move stuff out of Internal.* modules (basically just `foreing import`s as there will be no easy-ffi code anymore)

### CODE REVIEW

**Comment by dancingrobot84** [comment]
Hi! Thank you for the effort. However, there are two problems. First, such refactoring is going to be really big. Second, removing easyffi without proper test cases for each function is dangerous. I planned to write some tests next weekend and then start working on removing easyffi.

So, I suggest splitting changes in two PRs: this one will introduce `Aff` and the new one will replace easyffi. Also I'd like for you to wait until tests for internal functions is done and then start working on easyffi.

As for changes in this PR, they seem to be OK, except that, as I said before, it's better to put ffi changes aside.

**Comment by anttih** [comment]
Yes, agreed. Tests would be really nice. I'll try and split this PR.

**Comment by anttih** [comment]
This is now split into #26 and #27.

**Comment by dancingrobot84** [comment]
Great, thanks! As soon as tests are finished I will review and merge your changes.

**Comment by anttih** [comment]
I can rebase those branches on top of the new tests once they're ready.

**Comment by dancingrobot84** [comment]
Yeah, that would be great.

**Pull request closed without merging**
