### PR TITLE
Add subapp support

### PR DESCRIPTION
**Pull request by bramblex**
I add subapp support in purescript-express. Now you can mount sub app on other app. 
http://expressjs.com/en/api.html#app.mountpath

For example:

``` purescript
subAppIndexHandler :: forall eff. Handler eff
subAppIndexHandler = do
  send "This is subapp"

subapp :: forall eff. App eff
subapp = do
  get "/" subAppIndexHandler

main :: forall e. App (console :: CONSOLE | e)
main = do
  liftEff $ log "Setting up"
  mount "/subapp" subapp

```

### CODE REVIEW

**Comment by bramblex** [comment]
WTF …… `npm install purescript -g` failed ？

**Comment by dancingrobot84** [comment]
Hi! Thanks for the request. I've made a fix for failing Purescript installation, so if you rebase your changes   they should be built just fine :+1:

**Comment by bramblex** [comment]
I will write tests soon :smile:

**Comment by rvion** [comment]
any plan to continue this ? :)

**Comment by dancingrobot84** [comment]
Closing because it stayed open for over a year. Feel free to submit a new one if it's mergeable.

**Pull request closed without merging**
