### PR TITLE
Change module.require to require

### PR DESCRIPTION
**Pull request by ethul**
I am wondering if you would be interested in this small change that updates the `module.require` to just `require`. I found the call to `module.require` problematic when attempting to bundle up the compiled result as a node module.

If you are willing to accept this change, it would be most helpful.

Thanks!

### CODE REVIEW

**Comment by dancingrobot84** [comment]
Hi! Thanks for the contribution. These changes are already in review in #53. Can you please describe the issue with bundling in detail or give a link to a project that experience it?

**Comment by ethul** [comment]
Ah! Sorry for the duplicate PR. Please feel free to close this one.

The `module.require` is problematic when using webpack to generate a bundle that includes the compiled `purescript-express` library.

The reason that this doesn't work with webpack is the way that webpack appends all of the required modules together. Essentially, you get an array that looks something like:

```javascript
/******/ ([
  /* 0 */
  /*!********************!*\
    !*** ./src/first.js ***!
    \********************/
  /***/ function(module, exports, __webpack_require__) {

// Here you would have the module.require call.
// This fails because the module passed into this
// function wrapper does not have a function require.
exports.mkApplication = function() {
    var express = module.require('express');
    return express();
}
...

/***/ }
...,
/* n */
/*!***********************!*\
  !*** ./src/last.js ***!
  \***********************/
/***/ function(module, exports) {

      // some module

/***/ }
/******/ ]);
```

I hope that this makes sense. I am unsure if there is a work-around for webpack to make things work with `module.require`. But I am open to ideas.

**Comment by dancingrobot84** [comment]
Ah, ok, I see, thank you. Sure, I'll merge it.

**Comment by ethul** [comment]
Thanks!

**Pull request merged**
