### PR TITLE
Use plain ffi

### PR DESCRIPTION
**Pull request by anttih**
Needs #26. Relevant patch here is https://github.com/dancingrobot84/purescript-express/commit/c01d06e7a1434bb614022944de547ca2d60e37ae

### CODE REVIEW

**Comment by dancingrobot84** [comment]
@anttih Sorry for the long delay. I've almost finished tests, they are in `wip/tests` branch You could try to rebase your changes on it and see if everything works fine.

**Comment by anttih** [comment]
No worries, this is great. I'll rebase soon.

**Comment by stkb** [comment]
@anttih @dancingrobot84 Didn't want to step in on someone else's PR but can we get some movement on this? Am eager to see this and the Aff change go through and will help out any way I can.

**Comment by anttih** [comment]
Sorry I haven't worked on this. This needs to be rebased on top of the tests and make them pass. I'd gladly take patches to this branch to get this in. We should probably work on #26 first and then this.

**Comment by stkb** [comment]
Ok thanks. I'll take a look at your branches this weekend :)

**Comment by dancingrobot84** [comment]
Sorry for the long delay. This looks good. Thank you :+1:

**Pull request merged**
