### PR TITLE
Added response.end() method & moved the Test.unit package into bower dependencies

### PR DESCRIPTION
**Pull request by epicallan**
I moved the Test.unit package into bower dependencies because without it there you get this [build error](https://github.com/dancingrobot84/purescript-express/issues/66) another option was to move the Node.Express.Test.Mock module into the tests directory. I didn't go down that route because from earlier commits it seemed to have been moved into the src folder on purpose.

### CODE REVIEW

**Comment by dancingrobot84** [comment]
Thanks for the contribution! Looks good :+1:  However, the test case can be improved. Right now it doesn't check that `end` method is really called. You can remove the line `setupMockApp $ use end` and the test will still pass. One way to check the call is to add corresponding method into `MockResponse` [here](https://github.com/dancingrobot84/purescript-express/blob/master/src/Node/Express/Test/Mock.js) and make it do something, e.g. set a body to some predefined string. Later you can compare response body to that string and be sure that `end` is called.

**Comment by epicallan** [comment]
@dancingrobot84 thanks for the tip on how to rewrite the test case, will make those changes.

**Comment by epicallan** [comment]
@dancingrobot84 I made some changes to the tests as advised. I hope they suffice.

**Comment by dancingrobot84** [comment]
Good :+1:  Thank you!

**Pull request merged**
